import type { Car } from "./types";

export const MOCK_CARS: Car[] = [
  {
    id: "1",
    make: "Porsche",
    model: "911 GT3",
    year: 2023,
    price: 189500,
    mileage: 1200,
    fuelType: "Petrol",
    bodyType: "Coupe",
    imageUrl: "/cars/porsche.png",
    isNewArrival: true,
  },
  {
    id: "2",
    make: "Tesla",
    model: "Model S Plaid",
    year: 2022,
    price: 102900,
    mileage: 8400,
    fuelType: "Electric",
    bodyType: "Sedan",
    imageUrl: "/cars/tesla.png",
    isCertified: true,
  },
  {
    id: "3",
    make: "Range Rover",
    model: "Sport",
    year: 2024,
    price: 115000,
    mileage: 50,
    fuelType: "Hybrid",
    bodyType: "SUV",
    imageUrl: "/cars/range-rover.png",
  },
  {
    id: "4",
    make: "Mustang",
    model: "Shelby GT500",
    year: 1967,
    price: 245000,
    mileage: 15000,
    fuelType: "Petrol",
    bodyType: "Coupe",
    imageUrl: "/cars/mustang.png",
    isEditorsChoice: true,
    description:
      "Fully restored masterpiece featuring the legendary 428 Cobra Jet V8. A true icon of American muscle history.",
  },
  {
    id: "5",
    make: "Audi",
    model: "RS e-tron GT",
    year: 2023,
    price: 142000,
    mileage: 450,
    fuelType: "Electric",
    bodyType: "Sedan",
    imageUrl: "/cars/audi.png",
  },
];
